version: '3.7'

services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=testdb
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "pytest"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/testdb
      MINIO_HOST: minio:9000
    depends_on:
      - db
      - minio
  minio:
    image: minio/minio:latest
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
       MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin
    volumes:
     - minio-storage:/data
volumes:
  minio-storage:
  postgresql-data:
