"""Add table

Revision ID: 4b38c6ac301a
Revises: 3f768a556bdb
Create Date: 2022-06-20 14:08:06.667028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b38c6ac301a'
down_revision = '3f768a556bdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('ix_point_id', table_name='point')
    op.drop_table('point')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='point_pkey')
    )
    op.create_index('ix_point_id', 'point', ['id'], unique=False)
    op.drop_table('inbox')
    # ### end Alembic commands ###
