"""cut off millisecond

Revision ID: c28dccaffba6
Revises: 4b38c6ac301a
Create Date: 2022-06-20 14:47:30.184134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28dccaffba6'
down_revision = '4b38c6ac301a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inbox', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox', type_='unique')
    # ### end Alembic commands ###
